import img1 from '../../assets/imagesAvatar/img1.png';
import img2 from '../../assets/imagesAvatar/img2.png';
import img3 from '../../assets/imagesAvatar/img3.png';
import img4 from '../../assets/imagesAvatar/img4.png';
import img5 from '../../assets/imagesAvatar/img5.png';
import img6 from '../../assets/imagesAvatar/img6.png';
import img7 from '../../assets/imagesAvatar/img7.png';
import img8 from '../../assets/imagesAvatar/img8.png';
import img9 from '../../assets/imagesAvatar/img9.png';
import img10 from '../../assets/imagesAvatar/img10.png';
import img11 from '../../assets/imagesAvatar/img11.png';
import img12 from '../../assets/imagesAvatar/img12.png';
import img13 from '../../assets/imagesAvatar/img13.png';
import img14 from '../../assets/imagesAvatar/img14.png';
import img15 from '../../assets/imagesAvatar/img15.png';
import img16 from '../../assets/imagesAvatar/img16.png';


import moment from 'moment';
import uuid from 'uuid/v4'
import {performanceRate} from '../functions/miscellaneous'

export const sampleImgList = [
  img1, img2, img3, img4, img5, img6, img7, img8, img9, img10, img11, img12, img13, img14, img15, img16]

export const jobTitleList = [
  'Product Manager', 'UI/UX Designer', 'Backend Developer', 'Frontend Developer', 'Quality Assurance'
]

export const userList = [
  {
    id: uuid(),
    name:'Jason Bourne',
    jobTitle:'Product Manager',
    picture:img1,
    ongoingTaskTitle:'Comunicate to client and indept research for posible users',
    taskPercentage:20,
    overallTaskRating:3.5,
    performanceNote:'Need additional supervision',
    yearsExp:2,
    location:'202  Hickory Street, Salt Lake, Utah',
    contactNumber:'113-112-1245',
    maplocation:'',
    eMail:'jasonBourne@email.com',
    birthDate:moment('Mar. 18, 2003'),
    personalMessage:'',
    pitch:'Persistent and hard working',
    qaRating:2,
    feRating:1.5,
    beRating:1,
    designRating:3,
    prodMgtRating:5,
  },
  {
    id: uuid(),
    name:'Stephanie Jane Green',
    jobTitle:'UI/UX Designer',
    picture:img2,
    ongoingTaskTitle:'Design a wireframe for hiring sample',
    taskPercentage:40,
    overallTaskRating:4,
    performanceNote:'Knows her duty very well',
    yearsExp:3,
    location:'10  Hickory Street, Sweet Lake, California',
    contactNumber:'78-564-888',
    maplocation:'',
    eMail:'stephanieJaneGreen@email.com',
    birthDate:moment('Oct. 1, 2003'),
    personalMessage:'',
    pitch:'Specialize in wireframing and prototyping design',
    qaRating:1.5,
    feRating:1.5,
    beRating:1,
    designRating:5,
    prodMgtRating:2,
  },
  {
    id: uuid(),
    name:'Michael Joe Hofstader',
    jobTitle:'Backend Developer',
    picture:img3,
    ongoingTaskTitle:'Setup backend structure',
    taskPercentage:55,
    overallTaskRating:4.5,
    performanceNote:'Independent and fast',
    yearsExp:5,
    location:'10  Hickory Street, Sweet Lake, California',
    contactNumber:'78-564-888',
    maplocation:'',
    eMail:'michaelJoeHofstadder@email.com',
    birthDate:moment('Jan. 8, 2002'),
    personalMessage:'',
    pitch:'Experienced in different backend languages',
    qaRating:2,
    feRating:1.5,
    beRating:7,
    designRating:1.5,
    prodMgtRating:3,
  },
  {
    id: uuid(),
    name:'Steve Cooper',
    jobTitle:'Frontend Developer',
    picture:img4,
    ongoingTaskTitle:'Develop Frontend structure and Redux application',
    taskPercentage:75,
    overallTaskRating:4.5,
    performanceNote:'Coordinate well to backend and designer',
    yearsExp:10,
    location:'5016  West Fork Drive, Hollywood, Florida',
    contactNumber:'197-215-1123',
    maplocation:'',
    eMail:'steveCooper@email.com',
    birthDate:moment('Dec. 13, 1989'),
    personalMessage:'',
    pitch:'Well rounded Frontend master, knows all Frontend languages and experienced as fullstack developer',
    qaRating:3.5,
    feRating:10,
    beRating:8.5,
    designRating:9,
    prodMgtRating:6,
  },
  {
    id: uuid(),
    name:'Michelle Brand',
    jobTitle:'Frontend Developer',
    picture:img5,
    ongoingTaskTitle:'Create reusable components',
    taskPercentage:35,
    overallTaskRating:4,
    performanceNote:'Fast learner',
    yearsExp:2,
    location:'2524  Dark Hollow Road, Madison, Wisconsin',
    contactNumber:'920-11-5668',
    maplocation:'',
    eMail:'michelleBrand@email.com',
    birthDate:moment('Dec. 11, 1991'),
    personalMessage:'',
    pitch:'Likes frontend development and willing to learn deepeer',
    qaRating:1,
    feRating:2.5,
    beRating:4,
    designRating:2,
    prodMgtRating:2,
  },
  {
    id: uuid(),
    name:'Tracy Fowler',
    jobTitle:'Backend Developer',
    picture:img6,
    ongoingTaskTitle:'Use firebase for temporary storage',
    taskPercentage:70,
    overallTaskRating:3.5,
    performanceNote:'Need minimal supervision from backend',
    yearsExp:5,
    location:'825  Vine Street, Bensenville, Illinois',
    contactNumber:'920-302-5668',
    maplocation:'',
    eMail:'tracyFowler@email.com',
    birthDate:moment('June. 15, 1990'),
    personalMessage:'',
    pitch:'Good in deployment and Integration',
    qaRating:1,
    feRating:3,
    beRating:6.5,
    designRating:1,
    prodMgtRating:4,
  },
  {
    id: uuid(),
    name:'Isaac Norman West',
    jobTitle:'Quality Assurance',
    picture:img7,
    ongoingTaskTitle:'Creating Testcase secenario for user management',
    taskPercentage:50,
    overallTaskRating:4,
    performanceNote:'Independent',
    yearsExp:6,
    location:'122  Root Street, Bensenville, West Virginia',
    contactNumber:'1212-22-421',
    maplocation:'',
    eMail:'isaacNormanWest@email.com',
    birthDate:moment('July 8, 1992'),
    personalMessage:'',
    pitch:'Well verse in all QA',
    qaRating:8,
    feRating:1.5,
    beRating:1.3,
    designRating:1.5,
    prodMgtRating:5,
  },
]

export const availableCandidate = [
  {
    id: uuid(),
    name:'Cong Chooks',
    jobTitle:'Quality Assurance',
    picture:img7,
    ongoingTaskTitle:'',
    taskPercentage:0,
    overallTaskRating:0,
    performanceNote:'Newly hire',
    yearsExp:5,
    location:'362  Junkins Avenue, Nashville, Georgia',
    contactNumber:'229-745-0961',
    maplocation:'',
    eMail:'congChooks@email.com',
    birthDate:moment('Dec 13, 1989'),
    personalMessage:'',
    pitch:'Creating usecase testing and specializing in whitebox and blackbox testing',
    qaRating:6.5,
    feRating:2,
    beRating:1.5,
    designRating:4,
    prodMgtRating:4,
    


  },
  {
    id: uuid(),
    name:'Unique Lo',
    jobTitle:'Backend Developer',
    picture:img8,
    ongoingTaskTitle:'',
    taskPercentage:0,
    overallTaskRating:0,
    performanceNote:'Newly hire',
    yearsExp:1,
    location:'495  Berkshire Circle, BELLEVUE, Washington',
    contactNumber:'425-301-5583',
    maplocation:'',
    eMail:'uniqueLo@email.com',
    birthDate:moment('Jan, 30, 1992'),
    personalMessage:'',
    pitch:'Fast learner and perseverance is my key.',
    qaRating:1,
    feRating:2.3,
    beRating:3.7,
    designRating:2,
    prodMgtRating:4,
  },
  {
    id: uuid(),
    name:'Sam-Pon Lee Bo',
    jobTitle:'Frontend Developer',
    picture:img9,
    ongoingTaskTitle:'',
    taskPercentage:0,
    overallTaskRating:0,
    performanceNote:'Newly hire',
    yearsExp:2.5,
    location:'2032-1, Gwanghwamunucheguksaseoham, Jongro-gu, Seoul',
    contactNumber:'+82-2-883-1367',
    maplocation:'',
    eMail:'SamPonLeeBo@email.com',
    birthDate:moment('Sept. 20, 1987'),
    personalMessage:'',
    pitch:'Keen to details specially on designs',
    qaRating:1,
    feRating:4.5,
    beRating:3,
    designRating:4,
    prodMgtRating:1,
  },
  {
    id: uuid(),
    name:'Denver Collins',
    jobTitle:'Frontend Developer',
    picture:img10,
    ongoingTaskTitle:'',
    taskPercentage:0,
    overallTaskRating:0,
    performanceNote:'Newly hire',
    yearsExp:3,
    location:'1147  Ashton Lane, Milano, Texas',
    contactNumber:'832-256-2958',
    maplocation:'',
    eMail:'denverCollins@email.com',
    birthDate:moment('Sept. 5, 1995'),
    personalMessage:'',
    pitch:'Put my heart to every task and give a good output',
    qaRating:3,
    feRating:5.5,
    beRating:2,
    designRating:4,
    prodMgtRating:2.5,
  },
  {
    id: uuid(),
    name:'Justin Dave Kutrapalli',
    jobTitle:'Frontend Developer',
    picture:img11,
    ongoingTaskTitle:'',
    taskPercentage:0,
    overallTaskRating:0,
    performanceNote:'Newly hire',
    yearsExp:7,
    location:'4022  Young Road, Boise, Idaho',
    contactNumber:'208-391-1505',
    maplocation:'',
    eMail:'justinDaveKutrapalli@email.com',
    birthDate:moment('Aug. 10, 1983'),
    personalMessage:'',
    pitch:'Well rounded experience as a fullstack developer and focus on frontend development',
    qaRating:1.5,
    feRating:7,
    beRating:5,
    designRating:3,
    prodMgtRating:4.5,
  },
  {
    id: uuid(),
    name:'Sakura Suzuki',
    jobTitle:'Backend Developer',
    picture:img12,
    ongoingTaskTitle:'',
    taskPercentage:0,
    overallTaskRating:0,
    performanceNote:'Newly hire',
    yearsExp:10,
    location:'461-1246, Suguro, Ogawa-machi Hiki-gun, Saitama',
    contactNumber:'+8177-101-4754',
    maplocation:'',
    eMail:'sakuraSuzuki@email.com',
    birthDate:moment('Oct. 9, 1990'),
    personalMessage:'',
    pitch:'Focus on backend eversince I start in my career in IT industry.',
    qaRating:5,
    feRating:2.5,
    beRating:8,
    designRating:3,
    prodMgtRating:3.5,
  },
  {
    id: uuid(),
    name:'Spencer Bautista',
    jobTitle:'Backend Developer',
    picture:img13,
    ongoingTaskTitle:'',
    taskPercentage:0,
    overallTaskRating:0,
    performanceNote:'Newly hire',
    yearsExp:7,
    location:'Lot 5 Blk 4, 2021 street guiguinto, Bulacan',
    contactNumber:'794-23-1124',
    maplocation:'',
    eMail:'spencerBautista@email.com',
    birthDate:moment('Jan. 4, 1989'),
    personalMessage:'',
    pitch:'Know how to create Backend Architechtue',
    qaRating:2,
    feRating:4.5,
    beRating:8,
    designRating:1,
    prodMgtRating:5.5,
  },
  {
    id: uuid(),
    name:'Johanna Kris Webb',
    jobTitle:'UI/UX Designer',
    picture:img14,
    ongoingTaskTitle:'',
    taskPercentage:0,
    overallTaskRating:0,
    performanceNote:'Newly hire',
    yearsExp:5,
    location:'4742  Devils Hill Road, Brandon, Mississippi',
    contactNumber:'662-583-7908',
    maplocation:'',
    eMail:'johannaKrissWebb@email.com',
    birthDate:moment('Feb. 14, 2001'),
    personalMessage:'',
    pitch:'Specialized in creating landing page and Mobile Design',
    qaRating:4.5,
    feRating:2,
    beRating:1,
    designRating:6.8,
    prodMgtRating:3.5,
  },
  {
    id: uuid(),
    name:'Lea Honey Everett',
    jobTitle:'UI/UX Designer',
    picture:img15,
    ongoingTaskTitle:'',
    taskPercentage:0,
    overallTaskRating:0,
    performanceNote:'Newly hire',
    yearsExp:3,
    location:'2775  Pine Garden Lane, Brandon, Washinton',
    contactNumber:'404-667-4426',
    maplocation:'',
    eMail:'leahHoneyEverett@email.com',
    birthDate:moment('Feb. 14, 2001'),
    personalMessage:'',
    pitch:'Passed UI/UX Certification and focus on web application design',
    qaRating:2,
    feRating:3.5,
    beRating:2,
    designRating:6,
    prodMgtRating:5,
  },
  {
    id: uuid(),
    name:'Kirsty May Reid',
    jobTitle:'Product Manager',
    picture:img16,
    ongoingTaskTitle:'',
    taskPercentage:0,
    overallTaskRating:0,
    performanceNote:'Newly hire',
    yearsExp:0.5,
    location:'819  Hickory Street, Salt Lake, Utah',
    contactNumber:'404-112-1245',
    maplocation:'',
    eMail:'kristyMayReid@email.com',
    birthDate:moment('May. 05, 2005'),
    personalMessage:'',
    pitch:'Cumlaude in her school specialized in IT',
    qaRating:2,
    feRating:1,
    beRating:1.5,
    designRating:3,
    prodMgtRating:4,
  },
]







export const taskListFromBacklog = [
  {
    id: uuid(),
    ongoingTaskTitle:'Comunicate to client and indept research for posible users',
    name:'Jason Bourne',
    jobTitle:'Product Manager',
    picture:img1,
    completionDate: moment().add(7,'d'),
    dateStarted: moment(),
    dateCreated: moment().subtract(15,'d'),
    taskPercentage: 0,
    priorityLevel: 'urgent',
    difficultyLevel: 'easy',
    taskNote: `Must create a presentation and do a pitch day before the completion date.`,
    done:false,
    performanceRate:-1
  },
  {
    id: uuid(),
    ongoingTaskTitle:'Design a wireframe for hiring sample',
    name:'Stephanie Jane Green',
    jobTitle:'UI/UX Designer',
    picture:img2,
    completionDate: moment().add(10,'d'),
    dateStarted: moment(),
    dateCreated: moment().subtract(15,'d'),
    taskPercentage: 0,
    priorityLevel: 'normal',
    difficultyLevel: 'hard',
    taskNote: `Focus on Pastel Color, prefered blue and simplicity of project must be consider.`,
    done:false,
    performanceRate:-1
  },
  {
    id: uuid(),
    name:'Michael Joe Hofstader',
    jobTitle:'Backend Developer',
    picture:img3,
    ongoingTaskTitle:'Setup backend structure',
    completionDate: moment().add(9,'d'),
    dateStarted: moment(),
    dateCreated: moment().subtract(15,'d'),
    taskPercentage: 0,
    priorityLevel: 'least',
    difficultyLevel: 'medium',
    taskNote: `Coordinate first to PM and FE developer`,
    done:false,
    performanceRate:-1
  },
]


export const taskListFromTodo = [
  {
    id: uuid(),
    name:'Tracy Fowler',
    jobTitle:'Backend Developer',
    picture:img6,
    ongoingTaskTitle:'Use firebase for temporary storage',
    ongoingTaskTitle:'Develop Frontend structure and Redux application',
    completionDate: moment().add(5,'d'),
    dateStarted: moment(),
    dateCreated: moment().subtract(15,'d'),
    taskPercentage: 0,
    priorityLevel: 'urgent',
    difficultyLevel: 'hard',
    taskNote: `Create a documentation and structure analysis`,
    done:false,
    performanceRate:-1
  },
  
]



export const taskListFrominProgressId = [
  {
    id: uuid(),
    name:'Steve Cooper',
    jobTitle:'Frontend Developer',
    picture:img4,
    ongoingTaskTitle:'Develop Frontend structure and Redux application',
    completionDate: moment().add(5,'d'),
    dateStarted: moment().subtract(1,'d'),
    dateCreated: moment().subtract(15,'d'),
    taskPercentage: 75,
    priorityLevel: 'urgent',
    difficultyLevel: 'hard',
    taskNote: `Create a documentation and structure analysis`,
    done:false,
    performanceRate:-1
  },
  {
    id: uuid(),
    name:'Michelle Brand',
    jobTitle:'Frontend Developer',
    picture:img5,
    ongoingTaskTitle:'Create reusable components',
    taskPercentage:35,
    completionDate: moment().add(10,'d'),
    dateStarted: moment().subtract(1,'d'),
    dateCreated: moment().subtract(15,'d'),
    priorityLevel: 'least',
    difficultyLevel: 'hard',
    taskNote: `Coordinate to Steve Cooper to build the FE structure first`,
    done:false,
    performanceRate:-1
  },
  {
    id: uuid(),
    name:'Tracy Fowler',
    jobTitle:'Backend Developer',
    picture:img6,
    ongoingTaskTitle:'Use firebase for temporary storage',
    ongoingTaskTitle:'Develop Frontend structure and Redux application',
    completionDate: moment().add(5,'d'),
    dateStarted: moment(),
    dateCreated: moment().subtract(15,'d'),
    taskPercentage: 70,
    priorityLevel: 'urgent',
    difficultyLevel: 'hard',
    taskNote: `Create a documentation and structure analysis`,
    done:false,
    performanceRate:-1
  },
]

export const taskListFromRevision = []

export const taskListFromDone = [
  {
    id: uuid(),
    name:'Isaac Norman West',
    jobTitle:'Quality Assurance',
    picture:img7,
    ongoingTaskTitle:'Creating Testcase secenario for user management',
    taskPercentage:100,
    completionDate: moment(),
    dateStarted: moment().subtract(5,'d'),
    dateCreated: moment().subtract(15,'d'),
  
    priorityLevel: 'urgent',
    difficultyLevel: 'easy',
    taskNote: `Priority unit testing and create quick feedback`,
    done:true,
    performanceRate:1
  },
]

export const columnsFromBackend = 
{
  ['backlogId'] : {
    name: 'Backlog',
    items: taskListFromBacklog
  },
  ['inProgressId'] : {
    name: 'In Progress',
    items: taskListFrominProgressId
  },
  ['revisionId'] : {
    name: 'Bug to fix/For Revision',
    items: taskListFromRevision
  },
  ['doneId'] : {
    name: 'Done',
    items: taskListFromDone
  }
}

export const columnsEmpty = 
{
  ['backlogId'] : {
    name: 'Backlog',
    items: []
  },
  ['inProgressId'] : {
    name: 'In Progress',
    items: []
  },
  ['revisionId'] : {
    name: 'Bug to fix/For Revision',
    items: []
  },
  ['doneId'] : {
    name: 'Done',
    items: []
  }
}


export const taskHistoryList = [
  {
    year:'2020',
    month:'December',
    sprintNumber:1,
    lastSaveDate: moment().set('month', 11).set('year', 2020).set('date',14),
    taskHistory:[
      {
        id: uuid(),
        ongoingTaskTitle:'List the Initial feature requeted by the client',
        name:'Jason Bourne',
        jobTitle:'Product Manager',
        picture:img1,
        completionDate: moment().set('month', 11).set('year', 2020).add(1,'d'),
        dateStarted: moment().set('month', 11).set('year', 2020),
        dateCreated: moment().set('month', 11).set('year', 2020),
        taskPercentage:100,
        priorityLevel: 'urgent',
        difficultyLevel: 'easy',
        taskNote: `Pitch Must be simple`,
        done:true,
        performanceRate:1
        
      },
      {
        id: uuid(),
        ongoingTaskTitle:'Coordinate to Developers regarding the request of client',
        name:'Jason Bourne',
        jobTitle:'Product Manager',
        picture:img1,
        completionDate: moment().set('month', 11).set('year', 2020).set('date', 2),
        dateStarted: moment().set('month', 11).set('year', 2020).set('date', 1),
        dateCreated: moment().set('month', 11).set('year', 2020).set('date', 1),
        taskPercentage:100,
        priorityLevel: 'urgent',
        difficultyLevel: 'easy',
        taskNote: `Convert to simple and list all considerations from developers`,
        done:true,
        performanceRate:1
        
      },
      {
        id: uuid(),
        ongoingTaskTitle:'Write a letter for the initial approved feature to develop',
        name:'Jason Bourne',
        jobTitle:'Product Manager',
        picture:img1,
        completionDate: moment().set('month', 11).set('year', 2020).set('date', 3),
        dateStarted: moment().set('month', 11).set('year', 2020).set('date', 1),
        dateCreated: moment().set('month', 11).set('year', 2020).set('date', 1),
        taskPercentage:50,
        priorityLevel: 'urgent',
        difficultyLevel: 'easy',
        taskNote: `List down all of the item stated from the developer specially the timeline proposed`,
        done:false,
        performanceRate:-1
        
      },
      {
        id: uuid(),
        ongoingTaskTitle:'Design a wireframe for login',
        name:'Stephanie Jane Green',
        jobTitle:'UI/UX Designer',
        picture:img2,
        completionDate: moment().set('month', 11).set('year', 2020).set('date', 5),
        dateStarted: moment().set('month', 11).set('year', 2020).set('date', 3),
        dateCreated: moment().set('month', 11).set('year', 2020).set('date', 3),
        taskPercentage:100,
        priorityLevel: 'normal',
        difficultyLevel: 'hard',
        taskNote: `Do research and client based request`,
        done:true,
        performanceRate:4
        
      },
    ]
  },
  {
    year:'2020',
    month:'November',
    sprintNumber:1,
    lastSaveDate: moment().set('month', 10).set('year', 2020).set('date',14),
    taskHistory:[
      {
        id: uuid(),
        ongoingTaskTitle:'List the Initial feature requeted by the client',
        name:'Jason Bourne',
        jobTitle:'Product Manager',
        picture:img1,
        completionDate: moment().set('month', 10).set('year', 2020).add(1,'d'),
        dateStarted: moment().set('month', 10).set('year', 2020),
        dateCreated: moment().set('month', 10).set('year', 2020),
        taskPercentage:100,
        priorityLevel: 'urgent',
        difficultyLevel: 'easy',
        taskNote: `Pitch Must be simple`,
        done:true,
        performanceRate:1
        
      },
      {
        id: uuid(),
        ongoingTaskTitle:'Coordinate to Developers regarding the request of client',
        name:'Jason Bourne',
        jobTitle:'Product Manager',
        picture:img1,
        completionDate: moment().set('month', 10).set('year', 2020).set('date', 2),
        dateStarted: moment().set('month', 10).set('year', 2020).set('date', 1),
        dateCreated: moment().set('month', 10).set('year', 2020).set('date', 1),
        taskPercentage:100,
        priorityLevel: 'urgent',
        difficultyLevel: 'easy',
        taskNote: `Convert to simple and list all considerations from developers`,
        done:true,
        performanceRate:1
        
      },
      {
        id: uuid(),
        ongoingTaskTitle:'Write a letter for the initial approved feature to develop',
        name:'Jason Bourne',
        jobTitle:'Product Manager',
        picture:img1,
        completionDate: moment().set('month', 10).set('year', 2020).set('date', 3),
        dateStarted: moment().set('month', 10).set('year', 2020).set('date', 1),
        dateCreated: moment().set('month', 10).set('year', 2020).set('date', 1),
        taskPercentage:50,
        priorityLevel: 'urgent',
        difficultyLevel: 'easy',
        taskNote: `List down all of the item stated from the developer specially the timeline proposed`,
        done:false,
        performanceRate:-1
        
      },
      {
        id: uuid(),
        ongoingTaskTitle:'Design a wireframe for login',
        name:'Stephanie Jane Green',
        jobTitle:'UI/UX Designer',
        picture:img2,
        completionDate: moment().set('month', 10).set('year', 2020).set('date', 5),
        dateStarted: moment().set('month', 10).set('year', 2020).set('date', 3),
        dateCreated: moment().set('month', 10).set('year', 2020).set('date', 3),
        taskPercentage:100,
        priorityLevel: 'normal',
        difficultyLevel: 'hard',
        taskNote: `Do research and client based request`,
        done:true,
        performanceRate:4
        
      },
      {
        id: uuid(),
        ongoingTaskTitle:'Design a wireframe for Landing page and Hiring Page',
        name:'Stephanie Jane Green',
        jobTitle:'UI/UX Designer',
        picture:img2,
        completionDate: moment().set('month', 10).set('year', 2020).set('date', 12),
        dateStarted: moment().set('month', 10).set('year', 2020).set('date', 5),
        dateCreated: moment().set('month', 10).set('year', 2020).set('date', 5),
        taskPercentage:100,
        priorityLevel: 'normal',
        difficultyLevel: 'hard',
        taskNote: `Do research and client based request`,
        done:true,
        performanceRate:4
        
      },
      {
        id: uuid(),
        name:'Michael Joe Hofstader',
        jobTitle:'Backend Developer',
        picture:img3,
        ongoingTaskTitle:'Setup backend structure',
        completionDate: moment().set('month', 10).set('year', 2020).set('date', 10),
        dateStarted: moment().set('month', 10).set('year', 2020).set('date', 1),
        dateCreated: moment().set('month', 10).set('year', 2020).set('date', 1),
        taskPercentage:100,
        priorityLevel: 'least',
        difficultyLevel: 'medium',
        taskNote: `Do research for backend structure creation`,
        done:true,
        performanceRate:2
        
      },
      {
        id: uuid(),
        name:'Michael Joe Hofstader',
        jobTitle:'Backend Developer',
        picture:img3,
        ongoingTaskTitle:'Setup Database structure',
        completionDate: moment().set('month', 10).set('year', 2020).set('date',15),
        dateStarted: moment().set('month', 10).set('year', 2020).set('date', 2),
        dateCreated: moment().set('month', 10).set('year', 2020).set('date', 2),
        taskPercentage:100,
        priorityLevel: 'least',
        difficultyLevel: 'medium',
        taskNote: `Coordinate to frontend regarding the integration`,
        done:true,
        performanceRate:2
        
      },
      {
        id: uuid(),
        name:'Tracy Fowler',
        jobTitle:'Backend Developer',
        picture:img6,
        ongoingTaskTitle:'Research about the firebase',
        ongoingTaskTitle:'Develop Frontend structure and Redux application',
        completionDate: moment().set('month', 10).set('year', 2020).set('date',8),
        dateStarted: moment().set('month', 10).set('year', 2020).set('date', 1),
        dateCreated: moment().set('month', 10).set('year', 2020).set('date', 1),
        taskPercentage:100,
        priorityLevel: 'urgent',
        difficultyLevel: 'hard',
        taskNote: `Create a documentation and structure analysis`,
        done:true,
        performanceRate:5
        
      },
      {
        id: uuid(),
        name:'Steve Cooper',
        jobTitle:'Frontend Developer',
        picture:img4,
        ongoingTaskTitle:'Create a proposal regarding the frontend structure',
        completionDate: moment().set('month', 10).set('year', 2020).set('date',3),
        dateStarted: moment().set('month', 10).set('year', 2020).set('date', 1),
        dateCreated: moment().set('month', 10).set('year', 2020).set('date', 1),
        taskPercentage:100,
        priorityLevel: 'urgent',
        difficultyLevel: 'hard',
        taskNote: `Create a documentation`,
        done:true,
        performanceRate:5
        
      },
      {
        id: uuid(),
        name:'Steve Cooper',
        jobTitle:'Frontend Developer',
        picture:img4,
        ongoingTaskTitle:'Coordinate to all developers and pitch the proposed apporach',
        completionDate: moment().set('month', 10).set('year', 2020).set('date',6),
        dateStarted: moment().set('month', 10).set('year', 2020).set('date', 3),
        dateCreated: moment().set('month', 10).set('year', 2020).set('date', 1),
        taskPercentage:100,
        priorityLevel: 'urgent',
        difficultyLevel: 'hard',
        taskNote: `Create a documentation`,
        done:true,
        performanceRate:5
        
      },
      {
        id: uuid(),
        name:'Steve Cooper',
        jobTitle:'Frontend Developer',
        picture:img4,
        ongoingTaskTitle:'Initiate the Frontend structure',
        completionDate: moment().set('month', 10).set('year', 2020).set('date',10),
        dateStarted: moment().set('month', 10).set('year', 2020).set('date', 7),
        dateCreated: moment().set('month', 10).set('year', 2020).set('date', 1),
        taskPercentage:100,
        priorityLevel: 'urgent',
        difficultyLevel: 'hard',
        taskNote: `Create a documentation`,
        done:true,
        performanceRate:5
        
      },
      {
        id: uuid(),
        name:'Steve Cooper',
        jobTitle:'Frontend Developer',
        picture:img4,
        ongoingTaskTitle:'Apply Redux for data management',
        completionDate: moment().set('month', 10).set('year', 2020).set('date',14),
        dateStarted: moment().set('month', 10).set('year', 2020).set('date', 11),
        dateCreated: moment().set('month', 10).set('year', 2020).set('date', 1),
        taskPercentage:100,
        priorityLevel: 'urgent',
        difficultyLevel: 'hard',
        taskNote: `Create a documentation`,
        done:true,
        performanceRate:5
        
      },
      {
        id: uuid(),
        name:'Michelle Brand',
        jobTitle:'Frontend Developer',
        picture:img5,
        ongoingTaskTitle:'Study React/ Redux / Saga',
        taskPercentage:60,
        completionDate: moment().set('month', 10).set('year', 2020).set('date',14),
        dateStarted: moment().set('month', 10).set('year', 2020).set('date', 2),
        dateCreated: moment().set('month', 10).set('year', 2020).set('date', 1),
        priorityLevel: 'least',
        difficultyLevel: 'hard',
        taskNote: `Coordinate to Steve Cooper to build the FE structure first`,
        done:false,
        performanceRate:-1
        
      },
      {
        id: uuid(),
        name:'Isaac Norman West',
        jobTitle:'Quality Assurance',
        picture:img7,
        ongoingTaskTitle:'Creating Testcase secenario base on Initial feature requested',
        taskPercentage:100,
        completionDate: moment().set('month', 10).set('year', 2020).set('date',14),
        dateStarted: moment().set('month', 10).set('year', 2020).set('date', 1),
        dateCreated: moment().set('month', 10).set('year', 2020).set('date', 1),
      
        priorityLevel: 'urgent',
        difficultyLevel: 'easy',
        taskNote: `Double check all possible scenario`,
        done:true,
        performanceRate:3
        
      },
    ]
  },
  {
    year:'2020',
    month:'November',
    sprintNumber:2,
    lastSaveDate: moment().set('month', 10).set('year', 2020).set('date',28),
    taskHistory:[
      {
        id: uuid(),
        ongoingTaskTitle:'Coordinate to Developers regarding the request of client',
        name:'Jason Bourne',
        jobTitle:'Product Manager',
        picture:img1,
        completionDate: moment().set('month', 10).set('year', 2020).set('date', 22),
        dateStarted: moment().set('month', 10).set('year', 2020).set('date', 14),
        dateCreated: moment().set('month', 10).set('year', 2020).set('date', 14),
        taskPercentage:100,
        priorityLevel: 'urgent',
        difficultyLevel: 'easy',
        taskNote: `Convert to simple and list all considerations from developers`,
        done:true,
        performanceRate:3
        
      },
      {
        id: uuid(),
        ongoingTaskTitle:'Write a letter for the initial approved feature to develop',
        name:'Jason Bourne',
        jobTitle:'Product Manager',
        picture:img1,
        completionDate: moment().set('month', 10).set('year', 2020).set('date', 30),
        dateStarted: moment().set('month', 10).set('year', 2020).set('date', 22),
        dateCreated: moment().set('month', 10).set('year', 2020).set('date', 14),
        taskPercentage:100,
        priorityLevel: 'urgent',
        difficultyLevel: 'easy',
        taskNote: `List down all of the item stated from the developer specially the timeline proposed`,
        done:true,
        performanceRate:3
        
      },
      {
        id: uuid(),
        ongoingTaskTitle:'Design a wireframe for login',
        name:'Stephanie Jane Green',
        jobTitle:'UI/UX Designer',
        picture:img2,
        completionDate: moment().set('month', 10).set('year', 2020).set('date', 15),
        dateStarted: moment().set('month', 10).set('year', 2020).set('date', 13),
        dateCreated: moment().set('month', 10).set('year', 2020).set('date', 13),
        taskPercentage:100,
        priorityLevel: 'normal',
        difficultyLevel: 'hard',
        taskNote: `Do research and client based request`,
        done:true,
        performanceRate:4
        
      },
      {
        id: uuid(),
        ongoingTaskTitle:'Design a wireframe for Landing page and Hiring Page',
        name:'Stephanie Jane Green',
        jobTitle:'UI/UX Designer',
        picture:img2,
        completionDate: moment().set('month', 10).set('year', 2020).set('date', 30),
        dateStarted: moment().set('month', 10).set('year', 2020).set('date', 15),
        dateCreated: moment().set('month', 10).set('year', 2020).set('date', 15),
        taskPercentage:100,
        priorityLevel: 'normal',
        difficultyLevel: 'hard',
        taskNote: `Do research and client based request`,
        done:true,
        performanceRate:4
        
      },
      {
        id: uuid(),
        name:'Michael Joe Hofstader',
        jobTitle:'Backend Developer',
        picture:img3,
        ongoingTaskTitle:'Setup backend structure',
        completionDate: moment().set('month', 10).set('year', 2020).set('date', 30),
        dateStarted: moment().set('month', 10).set('year', 2020).set('date', 15),
        dateCreated: moment().set('month', 10).set('year', 2020).set('date', 15),
        taskPercentage:100,
        priorityLevel: 'least',
        difficultyLevel: 'medium',
        taskNote: `Do research for backend structure creation`,
        done:true,
        performanceRate:2
        
      },
      {
        id: uuid(),
        name:'Tracy Fowler',
        jobTitle:'Backend Developer',
        picture:img6,
        ongoingTaskTitle:'Research about the firebase',
        ongoingTaskTitle:'Develop Frontend structure and Redux application',
        completionDate: moment().set('month', 10).set('year', 2020).set('date',30),
        dateStarted: moment().set('month', 10).set('year', 2020).set('date', 15),
        dateCreated: moment().set('month', 10).set('year', 2020).set('date', 15),
        taskPercentage:100,
        priorityLevel: 'urgent',
        difficultyLevel: 'hard',
        taskNote: `Create a documentation and structure analysis`,
        done:true,
        performanceRate:5
        
      },
      {
        id: uuid(),
        name:'Steve Cooper',
        jobTitle:'Frontend Developer',
        picture:img4,
        ongoingTaskTitle:'Create a proposal regarding the frontend structure',
        completionDate: moment().set('month', 10).set('year', 2020).set('date',20),
        dateStarted: moment().set('month', 10).set('year', 2020).set('date', 14),
        dateCreated: moment().set('month', 10).set('year', 2020).set('date', 14),
        taskPercentage:100,
        priorityLevel: 'urgent',
        difficultyLevel: 'hard',
        taskNote: `Create a documentation`,
        done:true,
        performanceRate:5
        
      },
      {
        id: uuid(),
        name:'Steve Cooper',
        jobTitle:'Frontend Developer',
        picture:img4,
        ongoingTaskTitle:'Coordinate to all developers and pitch the proposed apporach',
        completionDate: moment().set('month', 10).set('year', 2020).set('date',29),
        dateStarted: moment().set('month', 10).set('year', 2020).set('date', 13),
        dateCreated: moment().set('month', 10).set('year', 2020).set('date', 11),
        taskPercentage:100,
        priorityLevel: 'urgent',
        difficultyLevel: 'hard',
        taskNote: `Create a documentation`,
        done:true,
        performanceRate:5
        
      },
      {
        id: uuid(),
        name:'Michelle Brand',
        jobTitle:'Frontend Developer',
        picture:img5,
        ongoingTaskTitle:'Study React/ Redux / Saga',
        taskPercentage:75,
        completionDate: moment().set('month', 10).set('year', 2020).set('date',30),
        dateStarted: moment().set('month', 10).set('year', 2020).set('date', 15),
        dateCreated: moment().set('month', 10).set('year', 2020).set('date', 14),
        priorityLevel: 'least',
        difficultyLevel: 'hard',
        taskNote: `Coordinate to Steve Cooper to build the FE structure first`,
        done:false,
        performanceRate:-1
        
      },
      {
        id: uuid(),
        name:'Isaac Norman West',
        jobTitle:'Quality Assurance',
        picture:img7,
        ongoingTaskTitle:'Creating Testcase secenario base on Initial feature requested',
        taskPercentage:100,
        completionDate: moment().set('month', 10).set('year', 2020).set('date',30),
        dateStarted: moment().set('month', 10).set('year', 2020).set('date', 15),
        dateCreated: moment().set('month', 10).set('year', 2020).set('date', 15),
      
        priorityLevel: 'urgent',
        difficultyLevel: 'easy',
        taskNote: `Double check all possible scenario`,
        done:true,
        performanceRate:1
        
      },
    ]
  },
  {
    year:'2020',
    month:'October',
    sprintNumber:1,
    lastSaveDate: moment().set('month', 9).set('year', 2020).set('date',14),
    taskHistory:[
      {
        id: uuid(),
        ongoingTaskTitle:'List the Initial feature requeted by the client',
        name:'Jason Bourne',
        jobTitle:'Product Manager',
        picture:img1,
        completionDate: moment().set('month', 9).set('year', 2020).add(1,'d'),
        dateStarted: moment().set('month', 9).set('year', 2020),
        dateCreated: moment().set('month', 9).set('year', 2020),
        taskPercentage:100,
        priorityLevel: 'urgent',
        difficultyLevel: 'easy',
        taskNote: `Pitch Must be simple`,
        done:true,
        performanceRate:1
        
      },
      {
        id: uuid(),
        ongoingTaskTitle:'Coordinate to Developers regarding the request of client',
        name:'Jason Bourne',
        jobTitle:'Product Manager',
        picture:img1,
        completionDate: moment().set('month', 9).set('year', 2020).set('date', 2),
        dateStarted: moment().set('month', 9).set('year', 2020).set('date', 1),
        dateCreated: moment().set('month', 9).set('year', 2020).set('date', 1),
        taskPercentage:100,
        priorityLevel: 'urgent',
        difficultyLevel: 'easy',
        taskNote: `Convert to simple and list all considerations from developers`,
        done:true,
        performanceRate:1
        
      },
      {
        id: uuid(),
        ongoingTaskTitle:'Write a letter for the initial approved feature to develop',
        name:'Jason Bourne',
        jobTitle:'Product Manager',
        picture:img1,
        completionDate: moment().set('month', 9).set('year', 2020).set('date', 3),
        dateStarted: moment().set('month', 9).set('year', 2020).set('date', 1),
        dateCreated: moment().set('month', 9).set('year', 2020).set('date', 1),
        taskPercentage:100,
        priorityLevel: 'urgent',
        difficultyLevel: 'easy',
        taskNote: `List down all of the item stated from the developer specially the timeline proposed`,
        done:true,
        performanceRate:1
        
      },
      {
        id: uuid(),
        ongoingTaskTitle:'Design a wireframe for login',
        name:'Stephanie Jane Green',
        jobTitle:'UI/UX Designer',
        picture:img2,
        completionDate: moment().set('month', 9).set('year', 2020).set('date', 5),
        dateStarted: moment().set('month', 9).set('year', 2020).set('date', 3),
        dateCreated: moment().set('month', 9).set('year', 2020).set('date', 3),
        taskPercentage:100,
        priorityLevel: 'normal',
        difficultyLevel: 'hard',
        taskNote: `Do research and client based request`,
        done:true,
        performanceRate:3
        
      },
      {
        id: uuid(),
        ongoingTaskTitle:'Design a wireframe for Landing page and Hiring Page',
        name:'Stephanie Jane Green',
        jobTitle:'UI/UX Designer',
        picture:img2,
        completionDate: moment().set('month', 9).set('year', 2020).set('date', 12),
        dateStarted: moment().set('month', 9).set('year', 2020).set('date', 5),
        dateCreated: moment().set('month', 9).set('year', 2020).set('date', 5),
        taskPercentage:100,
        priorityLevel: 'normal',
        difficultyLevel: 'hard',
        taskNote: `Do research and client based request`,
        done:true,
        performanceRate:3
        
      },
      {
        id: uuid(),
        name:'Michael Joe Hofstader',
        jobTitle:'Backend Developer',
        picture:img3,
        ongoingTaskTitle:'Setup backend structure',
        completionDate: moment().set('month', 9).set('year', 2020).set('date', 10),
        dateStarted: moment().set('month', 9).set('year', 2020).set('date', 1),
        dateCreated: moment().set('month', 9).set('year', 2020).set('date', 1),
        taskPercentage:100,
        priorityLevel: 'least',
        difficultyLevel: 'medium',
        taskNote: `Do research for backend structure creation`,
        done:true,
        performanceRate:2
        
      },
      {
        id: uuid(),
        name:'Michael Joe Hofstader',
        jobTitle:'Backend Developer',
        picture:img3,
        ongoingTaskTitle:'Setup Database structure',
        completionDate: moment().set('month', 9).set('year', 2020).set('date',15),
        dateStarted: moment().set('month', 9).set('year', 2020).set('date', 2),
        dateCreated: moment().set('month', 9).set('year', 2020).set('date', 2),
        taskPercentage:100,
        priorityLevel: 'least',
        difficultyLevel: 'medium',
        taskNote: `Coordinate to frontend regarding the integration`,
        done:true,
        performanceRate:2
        
      },
      {
        id: uuid(),
        name:'Tracy Fowler',
        jobTitle:'Backend Developer',
        picture:img6,
        ongoingTaskTitle:'Research about the firebase',
        ongoingTaskTitle:'Develop Frontend structure and Redux application',
        completionDate: moment().set('month', 9).set('year', 2020).set('date',8),
        dateStarted: moment().set('month', 9).set('year', 2020).set('date', 1),
        dateCreated: moment().set('month', 9).set('year', 2020).set('date', 1),
        taskPercentage:40,
        priorityLevel: 'urgent',
        difficultyLevel: 'hard',
        taskNote: `Create a documentation and structure analysis`,
        done:false,
        performanceRate:-1
        
      },
      {
        id: uuid(),
        name:'Steve Cooper',
        jobTitle:'Frontend Developer',
        picture:img4,
        ongoingTaskTitle:'Create a proposal regarding the frontend structure',
        completionDate: moment().set('month', 9).set('year', 2020).set('date',3),
        dateStarted: moment().set('month', 9).set('year', 2020).set('date', 1),
        dateCreated: moment().set('month', 9).set('year', 2020).set('date', 1),
        taskPercentage:100,
        priorityLevel: 'urgent',
        difficultyLevel: 'hard',
        taskNote: `Create a documentation`,
        done:true,
        performanceRate:5
        
      },
      {
        id: uuid(),
        name:'Steve Cooper',
        jobTitle:'Frontend Developer',
        picture:img4,
        ongoingTaskTitle:'Coordinate to all developers and pitch the proposed apporach',
        completionDate: moment().set('month', 9).set('year', 2020).set('date',6),
        dateStarted: moment().set('month', 9).set('year', 2020).set('date', 3),
        dateCreated: moment().set('month', 9).set('year', 2020).set('date', 1),
        taskPercentage:100,
        priorityLevel: 'urgent',
        difficultyLevel: 'hard',
        taskNote: `Create a documentation`,
        done:true,
        performanceRate:5
        
      },
      {
        id: uuid(),
        name:'Steve Cooper',
        jobTitle:'Frontend Developer',
        picture:img4,
        ongoingTaskTitle:'Initiate the Frontend structure',
        completionDate: moment().set('month', 9).set('year', 2020).set('date',10),
        dateStarted: moment().set('month', 9).set('year', 2020).set('date', 7),
        dateCreated: moment().set('month', 9).set('year', 2020).set('date', 1),
        taskPercentage:100,
        priorityLevel: 'urgent',
        difficultyLevel: 'hard',
        taskNote: `Create a documentation`,
        done:true,
        performanceRate:5
        
      },
      {
        id: uuid(),
        name:'Steve Cooper',
        jobTitle:'Frontend Developer',
        picture:img4,
        ongoingTaskTitle:'Apply Redux for data management',
        completionDate: moment().set('month', 9).set('year', 2020).set('date',14),
        dateStarted: moment().set('month', 9).set('year', 2020).set('date', 11),
        dateCreated: moment().set('month', 9).set('year', 2020).set('date', 1),
        taskPercentage:100,
        priorityLevel: 'urgent',
        difficultyLevel: 'hard',
        taskNote: `Create a documentation`,
        done:true,
        performanceRate:5
        
      },
      {
        id: uuid(),
        name:'Michelle Brand',
        jobTitle:'Frontend Developer',
        picture:img5,
        ongoingTaskTitle:'Study React/ Redux / Saga',
        taskPercentage:70,
        completionDate: moment().set('month', 9).set('year', 2020).set('date',14),
        dateStarted: moment().set('month', 9).set('year', 2020).set('date', 2),
        dateCreated: moment().set('month', 9).set('year', 2020).set('date', 1),
        priorityLevel: 'least',
        difficultyLevel: 'hard',
        taskNote: `Coordinate to Steve Cooper to build the FE structure first`,
        done:false,
        performanceRate:-1
        
      },
      {
        id: uuid(),
        name:'Isaac Norman West',
        jobTitle:'Quality Assurance',
        picture:img7,
        ongoingTaskTitle:'Creating Testcase secenario base on Initial feature requested',
        taskPercentage:80,
        completionDate: moment().set('month', 9).set('year', 2020).set('date',14),
        dateStarted: moment().set('month', 9).set('year', 2020).set('date', 1),
        dateCreated: moment().set('month', 9).set('year', 2020).set('date', 1),
      
        priorityLevel: 'urgent',
        difficultyLevel: 'easy',
        taskNote: `Double check all possible scenario`,
        done:false,
        performanceRate:-1
        
      },
    ]
  },
  {
    year:'2020',
    month:'October',
    sprintNumber:2,
    lastSaveDate: moment().set('month', 9).set('year', 2020).set('date',25),
    taskHistory:[
      {
        id: uuid(),
        ongoingTaskTitle:'Coordinate to Developers regarding the request of client',
        name:'Jason Bourne',
        jobTitle:'Product Manager',
        picture:img1,
        completionDate: moment().set('month', 9).set('year', 2020).set('date', 22),
        dateStarted: moment().set('month', 9).set('year', 2020).set('date', 14),
        dateCreated: moment().set('month', 9).set('year', 2020).set('date', 14),
        taskPercentage:100,
        priorityLevel: 'urgent',
        difficultyLevel: 'easy',
        taskNote: `Convert to simple and list all considerations from developers`,
        done:true,
        performanceRate:1
        
      },
      {
        id: uuid(),
        ongoingTaskTitle:'Write a letter for the initial approved feature to develop',
        name:'Jason Bourne',
        jobTitle:'Product Manager',
        picture:img1,
        completionDate: moment().set('month', 9).set('year', 2020).set('date', 30),
        dateStarted: moment().set('month', 9).set('year', 2020).set('date', 22),
        dateCreated: moment().set('month', 9).set('year', 2020).set('date', 14),
        taskPercentage:70,
        priorityLevel: 'urgent',
        difficultyLevel: 'easy',
        taskNote: `List down all of the item stated from the developer specially the timeline proposed`,
        done:false,
        performanceRate:-1
        
      },
      {
        id: uuid(),
        ongoingTaskTitle:'Design a wireframe for login',
        name:'Stephanie Jane Green',
        jobTitle:'UI/UX Designer',
        picture:img2,
        completionDate: moment().set('month', 9).set('year', 2020).set('date', 15),
        dateStarted: moment().set('month', 9).set('year', 2020).set('date', 13),
        dateCreated: moment().set('month', 9).set('year', 2020).set('date', 13),
        taskPercentage:100,
        priorityLevel: 'normal',
        difficultyLevel: 'hard',
        taskNote: `Do research and client based request`,
        done:true,
        performanceRate:4
        
      },
      {
        id: uuid(),
        ongoingTaskTitle:'Design a wireframe for Landing page and Hiring Page',
        name:'Stephanie Jane Green',
        jobTitle:'UI/UX Designer',
        picture:img2,
        completionDate: moment().set('month', 9).set('year', 2020).set('date', 30),
        dateStarted: moment().set('month', 9).set('year', 2020).set('date', 15),
        dateCreated: moment().set('month', 9).set('year', 2020).set('date', 15),
        taskPercentage:100,
        priorityLevel: 'normal',
        difficultyLevel: 'hard',
        taskNote: `Do research and client based request`,
        done:true,
        performanceRate:4
        
      },
      {
        id: uuid(),
        name:'Michael Joe Hofstader',
        jobTitle:'Backend Developer',
        picture:img3,
        ongoingTaskTitle:'Setup backend structure',
        completionDate: moment().set('month', 9).set('year', 2020).set('date', 30),
        dateStarted: moment().set('month', 9).set('year', 2020).set('date', 15),
        dateCreated: moment().set('month', 9).set('year', 2020).set('date', 15),
        taskPercentage:100,
        priorityLevel: 'least',
        difficultyLevel: 'medium',
        taskNote: `Do research for backend structure creation`,
        done:true,
        performanceRate:2
        
      },
      {
        id: uuid(),
        name:'Tracy Fowler',
        jobTitle:'Backend Developer',
        picture:img6,
        ongoingTaskTitle:'Research about the firebase',
        ongoingTaskTitle:'Develop Frontend structure and Redux application',
        completionDate: moment().set('month', 9).set('year', 2020).set('date',30),
        dateStarted: moment().set('month', 9).set('year', 2020).set('date', 15),
        dateCreated: moment().set('month', 9).set('year', 2020).set('date', 15),
        taskPercentage:100,
        priorityLevel: 'urgent',
        difficultyLevel: 'hard',
        taskNote: `Create a documentation and structure analysis`,
        done:true,
        performanceRate:5
        
      },
      {
        id: uuid(),
        name:'Steve Cooper',
        jobTitle:'Frontend Developer',
        picture:img4,
        ongoingTaskTitle:'Create a proposal regarding the frontend structure',
        completionDate: moment().set('month', 9).set('year', 2020).set('date',20),
        dateStarted: moment().set('month', 9).set('year', 2020).set('date', 14),
        dateCreated: moment().set('month', 9).set('year', 2020).set('date', 14),
        taskPercentage:100,
        priorityLevel: 'urgent',
        difficultyLevel: 'hard',
        taskNote: `Create a documentation`,
        done:true,
        performanceRate:5
        
      },
      {
        id: uuid(),
        name:'Steve Cooper',
        jobTitle:'Frontend Developer',
        picture:img4,
        ongoingTaskTitle:'Coordinate to all developers and pitch the proposed apporach',
        completionDate: moment().set('month', 9).set('year', 2020).set('date',29),
        dateStarted: moment().set('month', 9).set('year', 2020).set('date', 13),
        dateCreated: moment().set('month', 9).set('year', 2020).set('date', 11),
        taskPercentage:100,
        priorityLevel: 'urgent',
        difficultyLevel: 'hard',
        taskNote: `Create a documentation`,
        done:true,
        performanceRate:5
        
      },
      {
        id: uuid(),
        name:'Michelle Brand',
        jobTitle:'Frontend Developer',
        picture:img5,
        ongoingTaskTitle:'Study React/ Redux / Saga',
        taskPercentage:80,
        completionDate: moment().set('month', 9).set('year', 2020).set('date',30),
        dateStarted: moment().set('month', 9).set('year', 2020).set('date', 15),
        dateCreated: moment().set('month', 9).set('year', 2020).set('date', 14),
        priorityLevel: 'least',
        difficultyLevel: 'hard',
        taskNote: `Coordinate to Steve Cooper to build the FE structure first`,
        done:false,
        performanceRate:5
        
      },
      {
        id: uuid(),
        name:'Isaac Norman West',
        jobTitle:'Quality Assurance',
        picture:img7,
        ongoingTaskTitle:'Creating Testcase secenario base on Initial feature requested',
        taskPercentage:100,
        completionDate: moment().set('month', 9).set('year', 2020).set('date',30),
        dateStarted: moment().set('month', 9).set('year', 2020).set('date', 15),
        dateCreated: moment().set('month', 9).set('year', 2020).set('date', 15),
      
        priorityLevel: 'urgent',
        difficultyLevel: 'easy',
        taskNote: `Double check all possible scenario`,
        done:true,
        performanceRate:3
        
      },
    ]
  },
]