export const actionTypes = {
  FETCH_PERSONEL_LIST: 'FETCH_PERSONEL_LIST',
  UPDATE_PERSONEL_LIST:'UPDATE_PERSONEL_LIST',
  UPDATE_CANDIDATE_LIST:'UPDATE_CANDIDATE_LIST',
  UPDATE_TASK_LIST:'UPDATE_TASK_LIST',
  UPDATE_TASK_LIST_HISTORY:'UPDATE_TASK_LIST_HISTORY'
}
